dagster:
  image:
    repository: xiaoleng-dagster
    tag: latest
  runWorkerReplicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

postgresql:
  postgresqlUsername: dagster
  postgresqlDatabase: dagster
  persistence:
    enabled: true
    size: 10Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: dagster.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 