apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-home-pvc
  namespace: dagster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: xiaoleng-nas-jxgc9 