apiVersion: v1
kind: Service
metadata:
  name: dagster-postgresql
  labels:
    app: dagster-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: dagster-postgresql 