apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-postgresql-pvc
  namespace: dagster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-disk-essd 
