image:
  repository: crpi-zvc92t55tucy7jw0.cn-qingdao.personal.cr.aliyuncs.com/alignbase/dagster
  tag: 0.0.18
  imagePullSecrets:
    - name: acr-secret

webserver:
  enabled: true
  replicas: 1

daemon:
  enabled: true
  replicas: 1

persistence:
  enabled: true
  storageClass: xiaoleng-nas-jxgc9
  accessMode: ReadWriteMany
  size: 1Gi

postgresql:
  enabled: true
  auth:
    username: dagster
    password: dagster
    database: dagster
  primary:
    persistence:
      enabled: true
      storageClass: alicloud-disk-essd
      size: 10Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: dagster.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 
